test:
  prueba:
    url: http://192.168.0.101:8099/micro-cli/api_client
    saludi: HOLA JOSE

server:
  port: 8081
spring:
  data:
    mongodb:
      database: bdaccounts
      uri: mongodb+srv://user_mongo:G1TFNZUPitWXoy8z@cluster0.7dn2n.mongodb.net/bdaccounts?retryWrites=true&w=majority
      repositories:
        type: auto
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka