server:
  port: 80
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
spring:
  data:
    mongodb:
      database: bdclients
      uri: mongodb+srv://user_mongo:G1TFNZUPitWXoy8z@cluster0.7dn2n.mongodb.net/bdclients?retryWrites=true&w=majority
      repositories:
        type: auto
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/